---

- name: Pull image
  docker_image:
    name: sakshi1713/ci-cd-app
    tag: latest
    source: pull

- name: Run container
  docker_container:
    name: cicd-app
    image: sakshi1713/ci-cd-app:latest
    state: started
    ports:
      - "8080:8080"
